import { Cafe, Produtor } from './types';

export const MOCK_PRODUTORES: Produtor[] = [
  {
    id: 'prod-1',
    nome: 'Fazenda Santa Inês',
    regiao: 'Mantiqueira de Minas',
    estado: 'MG',
    descricao: 'Uma das fazendas mais premiadas do Brasil, com cafés de altitude excepcionais.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-2',
    nome: 'Sítio Bom Jesus',
    regiao: 'Chapada Diamantina',
    estado: 'BA',
    descricao: 'Produção orgânica certificada com terroir único do semiárido baiano.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-3',
    nome: 'Fazenda Ambiental Fortaleza',
    regiao: 'Mogiana',
    estado: 'SP',
    descricao: 'Pioneira em práticas sustentáveis e cafés naturais de alta qualidade.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-4',
    nome: 'Carmo Coffees',
    regiao: 'Sul de Minas',
    estado: 'MG',
    descricao: 'Especializada em microlotes de processamento especial.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-5',
    nome: 'Daterra Coffee',
    regiao: 'Cerrado Mineiro',
    estado: 'MG',
    descricao: 'Referência mundial em sustentabilidade e rastreabilidade.',
    avatar_url: null,
    created_at: new Date().toISOString()
  }
];

export const MOCK_CAFES: Cafe[] = [
  {
    id: 'cafe-1',
    produtor_id: 'prod-1',
    nome: 'Yellow Bourbon Natural',
    descricao: 'Um café lendário, vencedor de múltiplos campeonatos. Notas intensas de frutas tropicais e mel.',
    regiao: 'Mantiqueira de Minas',
    score_sca: 90.5,
    acidez: 2,
    docura: 5,
    corpo: 3,
    amargor: 1,
    intensidade: 3,
    notas_sensoriais: ['Frutas Tropicais', 'Mel', 'Caramelo', 'Chocolate ao Leite'],
    imagem_url: '/images/produto-graos-bourbon.png',
    ativo: true,
    preco: 98.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[0]
  },
  {
    id: 'cafe-2',
    produtor_id: 'prod-2',
    nome: 'Catuaí Honey',
    descricao: 'Processamento honey que realça a doçura natural do grão com notas de frutas vermelhas.',
    regiao: 'Chapada Diamantina',
    score_sca: 87.0,
    acidez: 4,
    docura: 4,
    corpo: 2,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Ameixa', 'Mel', 'Floral'],
    imagem_url: '/images/produto-graos-catuai.png',
    ativo: true,
    preco: 79.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[1]
  },
  {
    id: 'cafe-3',
    produtor_id: 'prod-3',
    nome: 'Bourbon Amarelo Cereja Natural',
    descricao: 'Café natural de altitude com perfil frutal marcante e acidez equilibrada.',
    regiao: 'Mogiana',
    score_sca: 88.5,
    acidez: 3,
    docura: 4,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Caramelo', 'Laranja', 'Baunilha', 'Castanhas'],
    imagem_url: '/images/produto-moido.png',
    ativo: true,
    preco: 85.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[2]
  },
  {
    id: 'cafe-4',
    produtor_id: 'prod-4',
    nome: 'Microlote Geisha',
    descricao: 'Um Geisha excepcional com notas florais delicadas e acidez brilhante.',
    regiao: 'Sul de Minas',
    score_sca: 92.0,
    acidez: 5,
    docura: 3,
    corpo: 2,
    amargor: 1,
    intensidade: 2,
    notas_sensoriais: ['Floral', 'Jasmim', 'Frutas Cítricas', 'Pêssego'],
    imagem_url: '/images/produto-microlote.png',
    ativo: true,
    preco: 145.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[3]
  },
  {
    id: 'cafe-5',
    produtor_id: 'prod-5',
    nome: 'Sweet Collection',
    descricao: 'Blend cuidadosamente selecionado para um perfil equilibrado e versátil.',
    regiao: 'Cerrado Mineiro',
    score_sca: 86.0,
    acidez: 2,
    docura: 4,
    corpo: 4,
    amargor: 3,
    intensidade: 4,
    notas_sensoriais: ['Chocolate', 'Caramelo', 'Castanhas', 'Especiarias'],
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 72.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[4]
  },
  {
    id: 'cafe-6',
    produtor_id: 'prod-1',
    nome: 'Mundo Novo Natural',
    descricao: 'Corpo intenso e notas de chocolate amargo, ideal para espresso.',
    regiao: 'Mantiqueira de Minas',
    score_sca: 85.5,
    acidez: 2,
    docura: 3,
    corpo: 5,
    amargor: 4,
    intensidade: 5,
    notas_sensoriais: ['Chocolate Amargo', 'Tabaco', 'Especiarias', 'Castanhas'],
    imagem_url: '/images/produto-graos-bourbon.png',
    ativo: true,
    preco: 76.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[0]
  },
  {
    id: 'cafe-7',
    produtor_id: 'prod-2',
    nome: 'Typica Fermentado',
    descricao: 'Fermentação controlada que cria notas únicas e complexas.',
    regiao: 'Chapada Diamantina',
    score_sca: 89.0,
    acidez: 4,
    docura: 3,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Vinho', 'Floral', 'Mel'],
    imagem_url: '/images/produto-graos-catuai.png',
    ativo: true,
    preco: 110.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[1]
  },
  {
    id: 'cafe-8',
    produtor_id: 'prod-4',
    nome: 'Catuaí Pulped Natural',
    descricao: 'Equilíbrio perfeito entre corpo e acidez com notas de frutas vermelhas.',
    regiao: 'Sul de Minas',
    score_sca: 87.5,
    acidez: 3,
    docura: 4,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Caramelo', 'Mel', 'Chocolate ao Leite'],
    imagem_url: '/images/produto-microlote.png',
    ativo: true,
    preco: 88.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[3]
  }
];
