import { Cafe, Produtor } from './types';

export const MOCK_PRODUTORES: Produtor[] = [
  {
    id: 'prod-1',
    nome: 'Fazenda Santa Inês',
    regiao: 'Mantiqueira de Minas',
    estado: 'MG',
    descricao: 'Uma das fazendas mais premiadas do Brasil, com cafés de altitude excepcionais.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-2',
    nome: 'Sítio Bom Jesus',
    regiao: 'Chapada Diamantina',
    estado: 'BA',
    descricao: 'Produção orgânica certificada com terroir único do semiárido baiano.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-3',
    nome: 'Fazenda Ambiental Fortaleza',
    regiao: 'Mogiana',
    estado: 'SP',
    descricao: 'Pioneira em práticas sustentáveis e cafés naturais de alta qualidade.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-4',
    nome: 'Carmo Coffees',
    regiao: 'Sul de Minas',
    estado: 'MG',
    descricao: 'Especializada em microlotes de processamento especial.',
    avatar_url: null,
    created_at: new Date().toISOString()
  },
  {
    id: 'prod-5',
    nome: 'Daterra Coffee',
    regiao: 'Cerrado Mineiro',
    estado: 'MG',
    descricao: 'Referência mundial em sustentabilidade e rastreabilidade.',
    avatar_url: null,
    created_at: new Date().toISOString()
  }
];

/** Gera as variações de peso padrão (250g/500g/1kg) a partir do preço base de 250g. */
function variantesPadrao(precoBase: number, disponibilidade: [boolean, boolean, boolean] = [true, true, true]) {
  return [
    { id: '250g', peso: '250g', preco: precoBase, disponivel: disponibilidade[0] },
    { id: '500g', peso: '500g', preco: Number((precoBase * 1.9).toFixed(2)), disponivel: disponibilidade[1] },
    { id: '1kg', peso: '1kg', preco: Number((precoBase * 3.6).toFixed(2)), disponivel: disponibilidade[2] }
  ];
}

const MOAGEM_OPCOES_PADRAO = [
  'Em grãos',
  'Espresso',
  'Moka',
  'Aeropress',
  'V60',
  'Chemex',
  'Prensa Francesa',
  'Filtro tradicional'
];

export const MOCK_CAFES: Cafe[] = [
  {
    id: 'cafe-1',
    produtor_id: 'prod-1',
    nome: 'Yellow Bourbon Natural',
    descricao: 'Um café lendário, vencedor de múltiplos campeonatos. Notas intensas de frutas tropicais e mel.',
    regiao: 'Mantiqueira de Minas',
    score_sca: 90.5,
    acidez: 2,
    docura: 5,
    corpo: 3,
    amargor: 1,
    intensidade: 3,
    notas_sensoriais: ['Frutas Tropicais', 'Mel', 'Caramelo', 'Chocolate ao Leite'],
    imagem_url: '/images/produto-graos-bourbon.png',
    ativo: true,
    preco: 98.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[0],

    slug: 'yellow-bourbon-natural',
    formato: 'graos',
    badge: 'Mais vendido',
    variantes: variantesPadrao(98.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Fazenda Santa Inês',
    variedade: 'Bourbon Amarelo',
    processo: 'Natural',
    torra: 'Média',
    altitude: '1.250m',
    safra: '2025',
    preparos: [
      {
        metodo: 'V60',
        cafe: '15g',
        agua: '250ml',
        temperatura: '92°C',
        moagem: 'Média',
        tempo: '2min30s a 3min'
      }
    ],
    estoque: 24
  },
  {
    id: 'cafe-2',
    produtor_id: 'prod-2',
    nome: 'Catuaí Honey',
    descricao: 'Processamento honey que realça a doçura natural do grão com notas de frutas vermelhas.',
    regiao: 'Chapada Diamantina',
    score_sca: 87.0,
    acidez: 4,
    docura: 4,
    corpo: 2,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Ameixa', 'Mel', 'Floral'],
    imagem_url: '/images/produto-graos-catuai.png',
    ativo: true,
    preco: 79.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[1],

    slug: 'catuai-honey',
    formato: 'graos',
    variantes: variantesPadrao(79.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Sítio Bom Jesus',
    variedade: 'Catuaí Vermelho',
    processo: 'Honey',
    torra: 'Média Clara',
    altitude: '980m',
    safra: '2025',
    preparos: [
      {
        metodo: 'Aeropress',
        cafe: '16g',
        agua: '220ml',
        temperatura: '88°C',
        moagem: 'Média-fina',
        tempo: '1min30s'
      }
    ],
    estoque: 18
  },
  {
    id: 'cafe-3',
    produtor_id: 'prod-3',
    nome: 'Bourbon Amarelo Cereja Natural',
    descricao: 'Café natural de altitude com perfil frutal marcante e acidez equilibrada.',
    regiao: 'Mogiana',
    score_sca: 88.5,
    acidez: 3,
    docura: 4,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Caramelo', 'Laranja', 'Baunilha', 'Castanhas'],
    imagem_url: '/images/produto-moido.png',
    ativo: true,
    preco: 85.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[2],

    slug: 'bourbon-amarelo-cereja-natural',
    formato: 'graos',
    badge: 'Oferta especial',
    preco_original: 99.00,
    variantes: variantesPadrao(85.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Fazenda Ambiental Fortaleza',
    variedade: 'Bourbon Amarelo',
    processo: 'Natural',
    torra: 'Média',
    altitude: '1.100m',
    safra: '2024',
    preparos: [
      {
        metodo: 'Chemex',
        cafe: '30g',
        agua: '500ml',
        temperatura: '94°C',
        moagem: 'Média-grossa',
        tempo: '4min'
      }
    ],
    estoque: 32
  },
  {
    id: 'cafe-4',
    produtor_id: 'prod-4',
    nome: 'Microlote Geisha',
    descricao: 'Um Geisha excepcional com notas florais delicadas e acidez brilhante.',
    regiao: 'Sul de Minas',
    score_sca: 92.0,
    acidez: 5,
    docura: 3,
    corpo: 2,
    amargor: 1,
    intensidade: 2,
    notas_sensoriais: ['Floral', 'Jasmim', 'Frutas Cítricas', 'Pêssego'],
    imagem_url: '/images/produto-microlote.png',
    ativo: true,
    preco: 145.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[3],

    slug: 'microlote-geisha',
    formato: 'graos',
    badge: 'Edição limitada',
    variantes: variantesPadrao(145.0, [true, true, false]),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Carmo Coffees',
    variedade: 'Geisha',
    processo: 'Lavado',
    torra: 'Clara',
    altitude: '1.400m',
    safra: '2025',
    preparos: [
      {
        metodo: 'V60',
        cafe: '13g',
        agua: '220ml',
        temperatura: '90°C',
        moagem: 'Média-fina',
        tempo: '2min45s'
      }
    ],
    estoque: 4
  },
  {
    id: 'cafe-5',
    produtor_id: 'prod-5',
    nome: 'Sweet Collection',
    descricao: 'Blend cuidadosamente selecionado para um perfil equilibrado e versátil.',
    regiao: 'Cerrado Mineiro',
    score_sca: 86.0,
    acidez: 2,
    docura: 4,
    corpo: 4,
    amargor: 3,
    intensidade: 4,
    notas_sensoriais: ['Chocolate', 'Caramelo', 'Castanhas', 'Especiarias'],
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 72.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[4],

    slug: 'sweet-collection',
    formato: 'graos',
    variantes: variantesPadrao(72.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Daterra Coffee',
    variedade: 'Blend (Catuaí + Mundo Novo)',
    processo: 'Cereja Descascado',
    torra: 'Média',
    altitude: '1.020m',
    safra: '2025',
    preparos: [
      {
        metodo: 'Prensa Francesa',
        cafe: '20g',
        agua: '300ml',
        temperatura: '95°C',
        moagem: 'Grossa',
        tempo: '4min'
      }
    ],
    estoque: 40
  },
  {
    id: 'cafe-6',
    produtor_id: 'prod-1',
    nome: 'Mundo Novo Natural',
    descricao: 'Corpo intenso e notas de chocolate amargo, ideal para espresso.',
    regiao: 'Mantiqueira de Minas',
    score_sca: 85.5,
    acidez: 2,
    docura: 3,
    corpo: 5,
    amargor: 4,
    intensidade: 5,
    notas_sensoriais: ['Chocolate Amargo', 'Tabaco', 'Especiarias', 'Castanhas'],
    imagem_url: '/images/produto-graos-bourbon.png',
    ativo: true,
    preco: 76.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[0],

    slug: 'mundo-novo-natural',
    formato: 'graos',
    variantes: variantesPadrao(76.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Fazenda Santa Inês',
    variedade: 'Mundo Novo',
    processo: 'Natural',
    torra: 'Escura',
    altitude: '1.180m',
    safra: '2024',
    preparos: [
      {
        metodo: 'Espresso',
        cafe: '18g',
        agua: '36ml',
        temperatura: '93°C',
        moagem: 'Fina',
        tempo: '25s a 30s'
      }
    ],
    estoque: 15
  },
  {
    id: 'cafe-7',
    produtor_id: 'prod-2',
    nome: 'Typica Fermentado',
    descricao: 'Fermentação controlada que cria notas únicas e complexas.',
    regiao: 'Chapada Diamantina',
    score_sca: 89.0,
    acidez: 4,
    docura: 3,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Vinho', 'Floral', 'Mel'],
    imagem_url: '/images/produto-graos-catuai.png',
    ativo: true,
    preco: 110.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[1],

    slug: 'typica-fermentado',
    formato: 'graos',
    variantes: variantesPadrao(110.0),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Sítio Bom Jesus',
    variedade: 'Typica',
    processo: 'Fermentado (48h)',
    torra: 'Média',
    altitude: '1.050m',
    safra: '2025',
    preparos: [
      {
        metodo: 'V60',
        cafe: '15g',
        agua: '250ml',
        temperatura: '91°C',
        moagem: 'Média',
        tempo: '2min45s'
      }
    ],
    estoque: 10
  },
  {
    id: 'cafe-8',
    produtor_id: 'prod-4',
    nome: 'Catuaí Pulped Natural',
    descricao: 'Equilíbrio perfeito entre corpo e acidez com notas de frutas vermelhas.',
    regiao: 'Sul de Minas',
    score_sca: 87.5,
    acidez: 3,
    docura: 4,
    corpo: 3,
    amargor: 2,
    intensidade: 3,
    notas_sensoriais: ['Frutas Vermelhas', 'Caramelo', 'Mel', 'Chocolate ao Leite'],
    imagem_url: '/images/produto-microlote.png',
    ativo: true,
    preco: 88.00,
    created_at: new Date().toISOString(),
    produtores: MOCK_PRODUTORES[3],

    slug: 'catuai-pulped-natural',
    formato: 'graos',
    variantes: variantesPadrao(88.0, [false, false, false]),
    moagem_opcoes: MOAGEM_OPCOES_PADRAO,
    origem: 'Brasil',
    fazenda: 'Carmo Coffees',
    variedade: 'Catuaí Vermelho',
    processo: 'Cereja Descascado',
    torra: 'Média',
    altitude: '1.150m',
    safra: '2024',
    preparos: [
      {
        metodo: 'Moka',
        cafe: '18g',
        agua: '150ml',
        temperatura: '95°C',
        moagem: 'Média-fina',
        tempo: '4min a 5min'
      }
    ],
    estoque: 0
  },

  // Moídos
  {
    id: 'cafe-9',
    produtor_id: null,
    nome: 'Café Pingado Bourbon Amarelo Moído 250g',
    descricao: 'O mesmo Bourbon Amarelo premiado, já moído no ponto ideal para coado.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-moido.png',
    ativo: true,
    preco: 46.90,
    created_at: new Date().toISOString(),

    slug: 'bourbon-amarelo-moido-250g',
    formato: 'moido',
    variantes: [{ id: '250g', peso: '250g', preco: 46.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 22
  },
  {
    id: 'cafe-10',
    produtor_id: null,
    nome: 'Café Pingado Prensa Francesa Moagem Grossa 250g',
    descricao: 'Moagem grossa pensada especialmente para prensa francesa, com corpo encorpado.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-moido.png',
    ativo: true,
    preco: 45.90,
    created_at: new Date().toISOString(),

    slug: 'prensa-francesa-moagem-grossa-250g',
    formato: 'moido',
    variantes: [{ id: '250g', peso: '250g', preco: 45.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 19
  },
  {
    id: 'cafe-11',
    produtor_id: null,
    nome: 'Café Pingado Espresso Moagem Fina 250g',
    descricao: 'Moagem fina para espresso encorpado, com crema densa e persistente.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-graos-catuai.png',
    ativo: true,
    preco: 49.90,
    created_at: new Date().toISOString(),

    slug: 'espresso-moagem-fina-250g',
    formato: 'moido',
    badge: 'Novo produtor',
    variantes: [{ id: '250g', peso: '250g', preco: 49.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 30
  },
  {
    id: 'cafe-12',
    produtor_id: null,
    nome: 'Café Pingado Coado Moagem Média 500g',
    descricao: 'Moagem média equilibrada, ideal para filtros de papel e coadores permanentes.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-moido.png',
    ativo: true,
    preco: 74.90,
    created_at: new Date().toISOString(),

    slug: 'coado-moagem-media-500g',
    formato: 'moido',
    variantes: [{ id: '500g', peso: '500g', preco: 74.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 14
  },

  // Drip Coffee
  {
    id: 'cafe-13',
    produtor_id: null,
    nome: 'Drip Coffee Pingado Mantiqueira Caixa 10un',
    descricao: 'Sachês individuais de drip coffee com café da Mantiqueira de Minas, prontos para coar direto na xícara.',
    regiao: 'Mantiqueira de Minas',
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 59.90,
    created_at: new Date().toISOString(),

    slug: 'drip-mantiqueira-10un',
    formato: 'drip',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 59.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 25
  },
  {
    id: 'cafe-14',
    produtor_id: null,
    nome: 'Drip Coffee Pingado Frutado Caixa 10un',
    descricao: 'Perfil frutado em sachês individuais, prático para o dia a dia sem abrir mão da qualidade.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 62.90,
    created_at: new Date().toISOString(),

    slug: 'drip-frutado-10un',
    formato: 'drip',
    badge: 'Novo produtor',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 62.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 20
  },
  {
    id: 'cafe-15',
    produtor_id: null,
    nome: 'Drip Coffee Pingado Intenso Caixa 20un',
    descricao: 'Perfil intenso e encorpado em caixa econômica de 20 sachês individuais.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 109.90,
    created_at: new Date().toISOString(),

    slug: 'drip-intenso-20un',
    formato: 'drip',
    variantes: [{ id: '20un', peso: 'Caixa 20un', preco: 109.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 11
  },
  {
    id: 'cafe-16',
    produtor_id: null,
    nome: 'Kit Degustação Drip Coffee 4 origens',
    descricao: 'Kit com quatro sachês de drip coffee, um de cada origem, para conhecer perfis diferentes.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-drip.png',
    ativo: true,
    preco: 89.90,
    created_at: new Date().toISOString(),

    slug: 'kit-degustacao-drip-4-origens',
    formato: 'drip',
    badge: 'Edição limitada',
    variantes: [{ id: '4un', peso: 'Kit 4un', preco: 89.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 9
  },

  // Cápsulas
  {
    id: 'cafe-17',
    produtor_id: null,
    nome: 'Cápsulas Pingado Bourbon Caixa 10un',
    descricao: 'Cápsulas de alumínio compatíveis com máquinas de espresso, com o perfil Bourbon Amarelo.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-capsulas.png',
    ativo: true,
    preco: 39.90,
    created_at: new Date().toISOString(),

    slug: 'capsulas-bourbon-10un',
    formato: 'capsula',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 39.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 28
  },
  {
    id: 'cafe-18',
    produtor_id: null,
    nome: 'Cápsulas Pingado Intenso Caixa 10un',
    descricao: 'Cápsulas de perfil intenso, com corpo marcante e torra mais escura.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-capsulas.png',
    ativo: true,
    preco: 41.90,
    created_at: new Date().toISOString(),

    slug: 'capsulas-intenso-10un',
    formato: 'capsula',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 41.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 17
  },
  {
    id: 'cafe-19',
    produtor_id: null,
    nome: 'Cápsulas Pingado Descafeinado Caixa 10un',
    descricao: 'Descafeinado com processo suave, mantendo aroma e sabor do café Pingado.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-capsulas.png',
    ativo: true,
    preco: 43.90,
    created_at: new Date().toISOString(),

    slug: 'capsulas-descafeinado-10un',
    formato: 'capsula',
    badge: 'Novo produtor',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 43.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 13
  },
  {
    id: 'cafe-20',
    produtor_id: null,
    nome: 'Cápsulas Pingado Microlote Caixa 10un',
    descricao: 'Edição limitada em cápsulas, com café de microlote raro selecionado pela curadoria.',
    regiao: null,
    score_sca: null,
    acidez: null,
    docura: null,
    corpo: null,
    amargor: null,
    intensidade: null,
    notas_sensoriais: null,
    imagem_url: '/images/produto-microlote.png',
    ativo: true,
    preco: 58.90,
    created_at: new Date().toISOString(),

    slug: 'capsulas-microlote-10un',
    formato: 'capsula',
    badge: 'Edição limitada',
    variantes: [{ id: '10un', peso: 'Caixa 10un', preco: 58.90, disponivel: true }],
    origem: 'Brasil',
    estoque: 6
  }
];
